drop table IF EXISTS ENTRENADORES;
create TABLE ENTRENADORES (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL);


insert into ENTRENADORES (NOMBRE) values ('Simon');
insert into ENTRENADORES (NOMBRE) values ('Pablo');